# Generated by Django 5.0.14 on 2026-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 Health Ave, New Delhi')),
                ('phone', models.CharField(default='+1 (558) 955-4885', max_length=50)),
                ('email', models.EmailField(default='info@medicare.com', max_length=254)),
            ],
        ),
    ]
